"""Generate a synthetic tabular dataset and save it to disk.

The script mirrors the data-generation logic of ``utils.load_and_split``:
it creates an imbalanced multi-class dataset with ``sklearn.make_classification``,
applies train/val/test stratified splits, fits a ``StandardScaler`` on the
training fold, and stores all six arrays (X/y for train, val, test) in a
single NumPy ``.npz`` file.

The saved file can be passed to ``sft.py`` or ``dpo.py`` via
``--dataset-path <file>`` to skip on-the-fly generation and ensure that
multiple fine-tuning runs operate on identical data.

Usage
-----
    python -m tabicl.finetune.make_data                          # all defaults
    python -m tabicl.finetune.make_data --output-path data/my_dataset.npz
    python -m tabicl.finetune.make_data --n-samples 2000 --n-classes 4

Type-annotated CLI arguments are parsed by tyro; run with ``--help`` for the
full option list.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import tyro

from tabicl.finetune.utils import load_and_split


# ---------------------------------------------------------------------------
# CLI configuration
# ---------------------------------------------------------------------------

@dataclass
class Config:
    # --- output -------------------------------------------------------------
    output_path: str = "data/dataset.npz"
    """Destination path for the saved ``.npz`` file."""

    # --- data generation ----------------------------------------------------
    val_size: float = 0.15
    """Fraction of the full dataset reserved for validation."""

    test_size: float = 0.15
    """Fraction of the full dataset reserved for held-out testing."""

    seed: int = 42
    """Random seed used for train/val/test splitting."""

    n_samples: int = 1000
    """Total number of samples generated by make_classification."""

    n_classes: int = 3
    """Number of target classes."""

    n_features: int = 20
    """Total number of features."""

    n_informative: int = 4
    """Number of informative features."""

    weights: list[float] = field(default_factory=lambda: [0.01, 0.01, 0.98])
    """Class weights (proportions) for make_classification. Length must equal n_classes."""

    dataset_random_state: int = 0
    """Random state passed to make_classification (independent of the split seed)."""


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(cfg: Config) -> None:
    X_train, y_train, X_val, y_val, X_test, y_test = load_and_split(cfg)

    out = Path(cfg.output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    np.savez(
        out,
        X_train=X_train, y_train=y_train,
        X_val=X_val,     y_val=y_val,
        X_test=X_test,   y_test=y_test,
    )
    print(f"Dataset saved to: {out}")


if __name__ == "__main__":
    cfg = tyro.cli(Config)
    main(cfg)
