"""Supervised fine-tuning (SFT) of TabICL with cross-entropy loss.

The script fine-tunes a pretrained TabICL checkpoint on a single
classification dataset.  It uses the model's _train_forward() path so
that gradients flow through every component.

Default dataset: imbalanced 3-class synthetic dataset (sklearn), split
into train / val / test.

Usage
-----
Activate the project venv, then:

    python -m tabicl.finetune.sft                       # all defaults
    python -m tabicl.finetune.sft --epochs 30 --lr 5e-6
    python -m tabicl.finetune.sft --output-dir runs/iris_sft --save-ckpt

Type-annotated CLI arguments are parsed by tyro; run with --help to see
the full list of options.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

import tyro
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from tabicl.finetune.utils import (
    set_seed,
    resolve_device,
    load_pretrained,
    apply_freeze,
    load_and_split,
    EpisodicDataset,
    collate_episodes,
    evaluate,
)


# ---------------------------------------------------------------------------
# CLI configuration (parsed by tyro)
# ---------------------------------------------------------------------------

@dataclass
class Config:
    # --- checkpoint ---------------------------------------------------------
    checkpoint_version: str = "tabicl-classifier-v2-20260212.ckpt"
    """HuggingFace filename of the pretrained TabICL checkpoint to start from."""

    checkpoint_path: Optional[str] = None
    """Local path to a checkpoint file.  If provided, skips HF Hub download."""

    # --- data ---------------------------------------------------------------
    val_size: float = 0.15
    """Fraction of the full dataset reserved for validation."""

    test_size: float = 0.15
    """Fraction of the full dataset reserved for held-out test evaluation."""

    seed: int = 42
    """Global random seed for reproducibility."""

    n_samples: int = 1000
    """Total number of samples generated by make_classification."""

    n_classes: int = 3
    """Number of target classes."""

    n_features: int = 20
    """Total number of features."""

    n_informative: int = 4
    """Number of informative features."""

    weights: list[float] = field(default_factory=lambda: [0.01, 0.01, 0.98])
    """Class weights (proportions) for make_classification. Length must equal n_classes."""

    dataset_random_state: int = 0
    """Random state passed to make_classification (independent of the training seed)."""

    # --- training -----------------------------------------------------------
    epochs: int = 5
    """Number of full passes over the training episodic batches."""

    batch_size: int = 16
    """Number of (train-context, test-query) episodes per gradient step.
    Each episode is built by resampling a random train/test split of the
    dataset, so the effective dataset is augmented across batches."""

    context_fraction: float = 0.7
    """Fraction of the episode's samples used as in-context training data;
    the remaining samples become query (test) points whose cross-entropy
    loss is optimised."""

    lr: float = 1e-5
    """AdamW learning rate (keep small to avoid catastrophic forgetting)."""

    weight_decay: float = 0.0
    """AdamW weight-decay coefficient."""

    gradient_clip: float = 1.0
    """Max-norm gradient clipping (0 = disabled)."""

    # --- freezing -----------------------------------------------------------
    freeze_col: bool = False
    """Freeze the column-embedding sub-network."""

    freeze_row: bool = False
    """Freeze the row-interaction sub-network."""

    freeze_icl: bool = False
    """Freeze the in-context-learning (ICL) sub-network."""

    # --- logging / saving ---------------------------------------------------
    output_dir: str = "runs/sft"
    """Directory for TensorBoard logs and (optionally) the saved checkpoint."""

    log_every: int = 10
    """Log training metrics to TensorBoard every this many steps."""

    val_every: int = 1
    """Run validation every this many epochs."""

    save_ckpt: bool = False
    """Save the fine-tuned model as `<output_dir>/tabicl_sft.ckpt` after training."""

    device: Optional[str] = None
    """Compute device (e.g. 'cpu', 'cuda', 'cuda:1').  Auto-detected if None."""


# ---------------------------------------------------------------------------
# Main training routine
# ---------------------------------------------------------------------------

def train(cfg: Config) -> None:
    set_seed(cfg.seed)
    device = resolve_device(cfg)
    output_dir = Path(cfg.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Device : {device}")
    print(f"Output : {output_dir}\n")

    # -- Data ----------------------------------------------------------------
    X_train, y_train, X_val, y_val, X_test, y_test = load_and_split(cfg)

    train_ds = EpisodicDataset(X_train, y_train, cfg.context_fraction, cfg.seed)
    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        collate_fn=collate_episodes,
        num_workers=0,
    )

    # -- Model ---------------------------------------------------------------
    model, model_config = load_pretrained(cfg)
    apply_freeze(model, cfg)
    model = model.to(device)

    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    n_total = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {n_trainable:,} trainable / {n_total:,} total\n")

    # -- Optimiser -----------------------------------------------------------
    optimizer = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=cfg.lr,
        weight_decay=cfg.weight_decay,
    )

    # -- Logging -------------------------------------------------------------
    writer = SummaryWriter(log_dir=str(output_dir))

    # -- Training loop -------------------------------------------------------
    global_step = 0
    best_val_acc = -1.0

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        epoch_loss = 0.0
        epoch_acc = 0.0
        epoch_precision = 0.0
        epoch_recall = 0.0
        epoch_f1 = 0.0
        n_batches = 0

        for X_batch, y_ctx_batch, y_qry_batch, ctx_sizes in train_loader:
            X_batch = X_batch.to(device)      # (B, T, H)
            y_ctx_batch = y_ctx_batch.to(device)  # (B, ctx_max) – float
            y_qry_batch = y_qry_batch.to(device)  # (B, qry_max) – int64

            optimizer.zero_grad(set_to_none=True)

            # model.train() → ICLearning.forward() already slices to test
            # positions internally (out = out[:, train_size:]), so the output
            # shape is (B, qry_size, max_classes) — NOT (B, T, max_classes).
            # We only need to restrict to the actual number of classes.
            ctx_size = ctx_sizes[0]
            logits_qry = model(
                X=X_batch,
                y_train=y_ctx_batch[:, :ctx_size],
            )  # (B, qry_size, max_classes)

            num_classes = int(y_ctx_batch.max().item()) + 1
            logits_qry  = logits_qry[:, :, :num_classes]  # (B, qry_size, C)

            # Flatten for cross-entropy; y_qry uses -100 as padding (ignored)
            B, Q, C = logits_qry.shape
            loss = F.cross_entropy(
                logits_qry.reshape(B * Q, C),
                y_qry_batch.reshape(B * Q),
                ignore_index=-100,
            )

            loss.backward()

            if cfg.gradient_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.gradient_clip)

            optimizer.step()

            # Metrics (ignoring padding)
            with torch.no_grad():
                mask = y_qry_batch.reshape(B * Q) != -100
                preds = logits_qry.reshape(B * Q, C).argmax(dim=-1)
                y_true_np = y_qry_batch.reshape(B * Q)[mask].cpu().numpy()
                preds_np = preds[mask].cpu().numpy()
                acc = accuracy_score(y_true_np, preds_np)
                precision = precision_score(y_true_np, preds_np, average="macro", zero_division=0)
                recall = recall_score(y_true_np, preds_np, average="macro", zero_division=0)
                f1 = f1_score(y_true_np, preds_np, average="macro", zero_division=0)

            epoch_loss += loss.item()
            epoch_acc += acc
            epoch_precision += precision
            epoch_recall += recall
            epoch_f1 += f1
            n_batches += 1
            global_step += 1

            if global_step % cfg.log_every == 0:
                writer.add_scalar("train/loss", loss.item(), global_step)
                writer.add_scalar("train/accuracy", acc, global_step)
                writer.add_scalar("train/precision", precision, global_step)
                writer.add_scalar("train/recall", recall, global_step)
                writer.add_scalar("train/f1", f1, global_step)
                writer.add_scalar(
                    "train/lr",
                    optimizer.param_groups[0]["lr"],
                    global_step,
                )

        avg_loss = epoch_loss / max(n_batches, 1)
        avg_acc = epoch_acc / max(n_batches, 1)
        avg_precision = epoch_precision / max(n_batches, 1)
        avg_recall = epoch_recall  / max(n_batches, 1)
        avg_f1 = epoch_f1 / max(n_batches, 1)
        print(
            f"Epoch {epoch:3d}/{cfg.epochs} — "
            f"train loss: {avg_loss:.4f}, acc: {avg_acc:.4f}, "
            f"prec: {avg_precision:.4f}, rec: {avg_recall:.4f}, f1: {avg_f1:.4f}",
            end="",
        )

        # -- Validation ------------------------------------------------------
        if epoch % cfg.val_every == 0:
            # Use all training data as context, validate on val set
            val_loss, val_acc, val_precision, val_recall, val_f1 = evaluate(
                model, X_train, y_train, X_val, y_val, device
            )
            writer.add_scalar("val/loss", val_loss, epoch)
            writer.add_scalar("val/accuracy", val_acc, epoch)
            writer.add_scalar("val/precision", val_precision, epoch)
            writer.add_scalar("val/recall", val_recall, epoch)
            writer.add_scalar("val/f1", val_f1, epoch)
            print(
                f"  |  val loss: {val_loss:.4f}, acc: {val_acc:.4f}, "
                f"prec: {val_precision:.4f}, rec: {val_recall:.4f}, f1: {val_f1:.4f}",
                end="",
            )

            if val_acc > best_val_acc:
                best_val_acc = val_acc

        print()  # newline after epoch line

    writer.close()
    print(f"\nBest validation accuracy: {best_val_acc:.4f}")

    # -- Test evaluation -----------------------------------------------------
    model.eval()
    test_loss, test_acc, test_precision, test_recall, test_f1 = evaluate(
        model, X_train, y_train, X_test, y_test, device
    )
    print(
        f"Test — loss: {test_loss:.4f}, acc: {test_acc:.4f}, "
        f"prec: {test_precision:.4f}, rec: {test_recall:.4f}, f1: {test_f1:.4f}"
    )

    # -- Save checkpoint -----------------------------------------------------
    if cfg.save_ckpt:
        save_path = output_dir / "tabicl_sft.ckpt"
        torch.save({"config": model_config, "state_dict": model.state_dict()}, save_path)
        print(f"\nFine-tuned checkpoint saved to: {save_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    cfg = tyro.cli(Config)
    train(cfg)
